### ISSUE TITLE
panic when q.Q() an empty *time.Time

### ISSUE THREAD

**Issue by leoviggiano** [ryboe/q#116]
q.Q panic when have to print an empty *time.Time

Version: v1.0.17
Steps to reproduce:
```go
var emptyDate *time.Time
q.Q(emptyDate)
```

Current result:
```go
emptyDate=%!v(PANIC=Format method: value method time.Time.GoString called using nil *Time pointer)
```

Expected result
```go
emptyDate=(*time.Time)(nil)
```

**Comment by hslatman** [comment]
This seems to have been fixed with the upgrade of [github.com/kr/pretty](https://github.com/kr/pretty) in https://github.com/ryboe/q/pull/117, which includes https://github.com/kr/pretty/commit/d8c7eb13a5c499cc7ccbeb58b3421b42c599bfae. 

Example output:

```console
[10:44:20 testq/main.go:17 main.main]
0.000s emptyDate=(*time.Time)(nil)
```

**Comment by ryboe** [comment]
That's great news! Thanks for letting me know! 🙂
