### ISSUE TITLE
qq log grows forever

### ISSUE THREAD

**Issue by variadico** [ryboe/q#2]
Currently, `q.log` can grow forever. It might be interesting if `qq` could rotate the log. Maybe we could add a `q.MaxFileSize` setting or something.

This even _might_ be an issue on Linux, if the temp dir contents get written to RAM instead of disk.

**Comment by XANi** [comment]
rotate-by-default is really annoying behaviour from sysadmin point of view as in many cases we want to just have config of all logs in one place and managed by `logrotate`. Also if you use that on production, you probably should use "proper" logging framework in the first place.
