### ISSUE TITLE
Consider moving to golangq/q

### ISSUE THREAD

**Issue by wxio** [ryboe/q#54]
Whilst I love the name y0ssar1an, catch-22 is one of my all time favourite books, I need to look up the spelling everytime I use the library. This is kinda counter to the idea behind q. 

Hence the suggestion to more the library to something more easily remember.

I have registered github.com/golangq, cloned q & added y0ssar1n as an owner.

**Comment by ryboe** [comment]
Sorry I ignored this issue for so long! I hope `ryboe/q` is a little easier to type and remember than `y0ssar1an/q`.
